// AUTO-GENERATED by tskm. Do not edit.

export type User = {
  name: string;
  age: number;
  address: {
    city: string;
    zip: string;
  };
}

export type Product = {
  id: string;
  price: number;
}
