// AUTO-GENERATED by tskm. Do not edit.

export type User = {
  readonly name: string;
  readonly age: number;
  readonly address: {
    readonly city: string;
    readonly zip: string;
  };
}

export type Product = {
  readonly id: string;
  readonly price: number;
}
