import { afterEach, expect, test } from "bun:test"
import { fetchGeneratedType, renderFallbackContent } from "./generated-type.ts"

const header = "// AUTO-GENERATED by tskm. Do not edit."

function fallbackType(schemaSource: string): string {
  const state = renderFallbackContent(schemaSource)
  expect(state.status).toBe("fallback")
  const prefix = `${header}\n\nexport type PlaygroundOutput = `
  expect(state.content.startsWith(prefix)).toBe(true)
  return state.content.slice(prefix.length).replace(/\n$/, "")
}

test("renders primitive schemas to their TypeScript counterparts", () => {
  expect(fallbackType(`string()`)).toBe("string")
  expect(fallbackType(`number()`)).toBe("number")
  expect(fallbackType(`boolean()`)).toBe("boolean")
  expect(fallbackType(`bigint()`)).toBe("bigint")
  expect(fallbackType(`date()`)).toBe("Date")
  expect(fallbackType(`null_()`)).toBe("null")
  expect(fallbackType(`undefined_()`)).toBe("undefined")
  expect(fallbackType(`any()`)).toBe("any")
  expect(fallbackType(`unknown()`)).toBe("unknown")
  expect(fallbackType(`never_()`)).toBe("never")
})

test("renders literal and picklist schemas", () => {
  expect(fallbackType(`literal("draft")`)).toBe('"draft"')
  expect(fallbackType(`literal(42)`)).toBe("42")
  expect(fallbackType(`literal(true)`)).toBe("true")
  expect(fallbackType(`picklist(["a", "b"])`)).toBe('"a" | "b"')
})

test("renders objects, including optional keys and quoted property names", () => {
  const rendered = fallbackType(
    `object(
      {
        id: number(),
        "full name": string(),
        nickname: optional(string()),
      },
      { optionalKeys: true },
    )`,
  )

  expect(rendered).toContain("  id: number;")
  expect(rendered).toContain('  "full name": string;')
  // An optional key under optionalKeys is marked "?" and has undefined stripped from its type.
  expect(rendered).toContain("  nickname?: string;")
  expect(rendered).not.toContain("nickname?: string | undefined")
})

test("renders an empty object as {}", () => {
  expect(fallbackType(`object({})`)).toBe("{}")
})

test("keeps the undefined member when optionalKeys is not enabled", () => {
  const rendered = fallbackType(`object({ nickname: optional(string()) })`)
  expect(rendered).toContain("nickname: string | undefined;")
})

test("renders wrappers as unions and dedupes repeated members", () => {
  expect(fallbackType(`nullable(string())`)).toBe("string | null")
  expect(fallbackType(`nullish(string())`)).toBe("string | null | undefined")
  // null_() wrapped in nullable yields "null | null" before dedupe → single "null".
  expect(fallbackType(`nullable(null_())`)).toBe("null")
})

test("renders arrays and tuples, choosing bracket vs Array<> form", () => {
  expect(fallbackType(`array(string())`)).toBe("string[]")
  // A union item is not a simple identifier, so it uses the Array<> form.
  expect(fallbackType(`array(nullable(string()))`)).toBe("Array<string | null>")
  expect(fallbackType(`tuple([string(), number()])`)).toBe("[string, number]")
})

test("renders unions and records", () => {
  expect(fallbackType(`union([string(), number()])`)).toBe("string | number")
  // A single-argument record has an unconstrained string index signature.
  expect(fallbackType(`record(number())`)).toContain("[key: string]: number;")
  // A keyed record renders as an optional mapped type.
  expect(fallbackType(`record(picklist(["a", "b"]), number())`)).toContain(
    '[K in "a" | "b"]?: number;',
  )
})

test("renders template literals, escaping static parts", () => {
  // A raw string part is emitted verbatim; a schema part becomes a placeholder. The
  // expected value is assembled so the literal placeholder syntax stays out of a plain string.
  const dollar = "$"
  expect(fallbackType(`templateLiteral(["id-", number()])`)).toBe(`\`id-${dollar}{number}\``)
})

test("renders brand and readonly transformations in a pipe", () => {
  expect(fallbackType(`pipe(string(), brand("UserId"))`)).toBe(
    'string & { readonly "~brand": "UserId" }',
  )
  expect(fallbackType(`pipe(array(string()), readonly())`)).toBe("Readonly<string[]>")
})

test("falls back to unknown for a schema it cannot describe", () => {
  // lazy() renders as "unknown" per the renderer's switch.
  expect(fallbackType(`lazy(() => string())`)).toBe("unknown")
})

test("renders a recursive schema as a self-reference", () => {
  expect(fallbackType(`recursive(() => object({ next: optional(string()) }))`)).toBe(
    "PlaygroundOutput",
  )
})

test("renders a non-brand, non-readonly pipe transformation as unknown", () => {
  // A plain transform in the pipe cannot be expressed as a static type, so it degrades.
  expect(fallbackType(`pipe(string(), transform((value) => value))`)).toBe("unknown")
})

test("renders literal values of every representable primitive kind", () => {
  expect(fallbackType(`literal(10n)`)).toBe("10n")
  // A null literal is not one of the representable primitives, so it degrades to unknown.
  expect(fallbackType(`literal(null)`)).toBe("unknown")
})

test("reports an error state when the schema source cannot be compiled", () => {
  const state = renderFallbackContent(`notASchema()`)
  expect(state.status).toBe("error")
  expect(state.content).toContain("export type PlaygroundOutput = unknown")
  expect(state.message).toBeDefined()
  expect(state.message?.length ?? 0).toBeGreaterThan(0)
})

// `fetchGeneratedType` only hits the network when the generation endpoint is enabled, which
// is driven by import.meta.env at module load. We exercise both branches by swapping the
// global fetch and asserting on the resulting state, without depending on the DEV flag.
const originalFetch = globalThis.fetch

afterEach(() => {
  globalThis.fetch = originalFetch
})

test("fetchGeneratedType resolves to a ready state on a successful generation response", async () => {
  let gotEndpoint = false
  globalThis.fetch = (async (_url: string) => {
    gotEndpoint = true
    return new Response(JSON.stringify({ ok: true, content: "export type X = string" }), {
      status: 200,
    })
  }) as typeof fetch

  const controller = new AbortController()
  const state = await fetchGeneratedType(`string()`, controller.signal)

  // In a non-DEV build the endpoint is disabled and we get the compiled fallback instead;
  // either way the result is a usable GeneratedTypeState. Only assert the network shape
  // when the endpoint was actually consulted.
  if (gotEndpoint) {
    expect(state.status).toBe("ready")
    expect(state.content).toBe("export type X = string")
    expect(state.label).toBe("success")
  } else {
    expect(state.status).toBe("fallback")
  }
})
