import { compileSchema } from "./run-schema.ts"

export interface GeneratedTypeState {
  readonly status: "loading" | "ready" | "fallback" | "error"
  readonly content: string
  readonly label: string
  readonly message?: string
  readonly diagnostics: readonly string[]
}

interface TskmGenSuccess {
  readonly ok: true
  readonly content: string
  readonly diagnostics?: readonly string[]
}

interface TskmGenFailure {
  readonly ok: false
  readonly message: string
  readonly diagnostics?: readonly string[]
}

type TskmGenResponse = TskmGenSuccess | TskmGenFailure

const header = "// AUTO-GENERATED by tskm. Do not edit."
const generationEndpoint = "/__tskm_playground/typegen"

export async function fetchGeneratedType(
  schemaSource: string,
  signal: AbortSignal,
): Promise<GeneratedTypeState> {
  const response = await fetch(generationEndpoint, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ schemaSource }),
    signal,
  })

  if (!response.ok) {
    throw new Error(`tskm gen endpoint returned ${response.status}`)
  }

  const result = (await response.json()) as TskmGenResponse
  if (result.ok) {
    return {
      status: "ready",
      content: result.content,
      label: "success",
      diagnostics: result.diagnostics ?? [],
    }
  }

  return {
    status: "error",
    content: renderFallbackContent(schemaSource).content,
    label: "preview",
    message: result.message,
    diagnostics: result.diagnostics ?? [],
  }
}

export function renderFallbackContent(schemaSource: string): GeneratedTypeState {
  try {
    const schema = compileSchema(schemaSource)
    return {
      status: "fallback",
      content: `${header}\n\nexport type PlaygroundOutput = ${renderSchema(schema)}\n`,
      label: "preview",
      diagnostics: [],
    }
  } catch (error) {
    return {
      status: "error",
      content: `${header}\n\nexport type PlaygroundOutput = unknown\n`,
      label: "preview",
      message: error instanceof Error ? error.message : String(error),
      diagnostics: [],
    }
  }
}

function renderSchema(schema: unknown, seen = new WeakSet<object>()): string {
  if (!isRecord(schema)) return "unknown"

  const pipe = schema.pipe
  if (Array.isArray(pipe) && pipe.length > 0) {
    return renderPipe(pipe, seen)
  }

  if (seen.has(schema)) return "PlaygroundOutput"
  seen.add(schema)

  switch (schema.type) {
    case "any":
      return "any"
    case "unknown":
      return "unknown"
    case "never":
      return "never"
    case "string":
      return "string"
    case "number":
      return "number"
    case "boolean":
      return "boolean"
    case "bigint":
      return "bigint"
    case "date":
      return "Date"
    case "null":
      return "null"
    case "undefined":
      return "undefined"
    case "literal":
      return renderLiteral(schema.literal)
    case "picklist":
      return Array.isArray(schema.options) ? schema.options.map(renderLiteral).join(" | ") : "never"
    case "array":
    case "arrayAsync":
      return renderArray(renderSchema(schema.item, seen))
    case "tuple":
      return Array.isArray(schema.items)
        ? `[${schema.items.map((item) => renderSchema(item, seen)).join(", ")}]`
        : "unknown[]"
    case "union":
    case "unionAsync":
    case "discriminated_union":
    case "discriminated_union_async":
      return Array.isArray(schema.options)
        ? schema.options.map((option) => renderSchema(option, seen)).join(" | ")
        : "unknown"
    case "object":
    case "objectAsync":
      return renderObject(schema, seen)
    case "record":
    case "recordAsync":
      return renderRecord(schema, seen)
    case "optional":
      return joinUnion([renderSchema(schema.wrapped, seen), "undefined"])
    case "nullable":
      return joinUnion([renderSchema(schema.wrapped, seen), "null"])
    case "nullish":
      return joinUnion([renderSchema(schema.wrapped, seen), "null", "undefined"])
    case "templateLiteral":
      return renderTemplateLiteral(schema, seen)
    case "lazy":
      return "unknown"
    case "recursive":
      return "PlaygroundOutput"
    default:
      return "unknown"
  }
}

function renderPipe(pipe: readonly unknown[], seen: WeakSet<object>): string {
  const [base, ...items] = pipe
  let rendered = renderSchema(base, seen)
  for (const item of items) {
    if (!isRecord(item)) continue
    if (item.kind !== "transformation") continue
    if (item.type === "brand") {
      rendered = `${rendered} & { readonly "~brand": ${renderLiteral(item.name)} }`
    } else if (item.type === "readonly") {
      rendered = `Readonly<${rendered}>`
    } else {
      rendered = "unknown"
    }
  }
  return rendered
}

function renderObject(schema: Record<string, unknown>, seen: WeakSet<object>): string {
  const entries = isRecord(schema.entries) ? schema.entries : {}
  const optionalKeys = schema.optionalKeys === true
  const lines = Object.entries(entries).map(([key, value]) => {
    const valueType = renderSchema(value, seen)
    const omittable =
      optionalKeys && isRecord(value) && (value.type === "optional" || value.type === "nullish")
    return `  ${propertyName(key)}${omittable ? "?" : ""}: ${
      omittable ? stripUndefined(valueType) : valueType
    };`
  })
  return lines.length > 0 ? `{\n${lines.join("\n")}\n}` : "{}"
}

function renderRecord(schema: Record<string, unknown>, seen: WeakSet<object>): string {
  const valueType = renderSchema(schema.value, seen)
  if (schema.key === undefined) {
    return `{\n  [key: string]: ${valueType};\n}`
  }
  return `{\n  [K in ${renderSchema(schema.key, seen)}]?: ${valueType};\n}`
}

function renderTemplateLiteral(schema: Record<string, unknown>, seen: WeakSet<object>): string {
  if (!Array.isArray(schema.parts)) return "string"
  return `\`${schema.parts
    .map((part) =>
      typeof part === "string" ? escapeTemplatePart(part) : `\${${renderSchema(part, seen)}}`,
    )
    .join("")}\``
}

function renderArray(itemType: string): string {
  return /^[\w.$`"']+$/.test(itemType) ? `${itemType}[]` : `Array<${itemType}>`
}

function renderLiteral(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(value)
  if (typeof value === "number" || typeof value === "boolean") return String(value)
  if (typeof value === "bigint") return `${value}n`
  if (typeof value === "symbol") return "symbol"
  return "unknown"
}

function propertyName(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key)
}

function stripUndefined(value: string): string {
  return value
    .split(" | ")
    .filter((part) => part !== "undefined")
    .join(" | ")
}

function joinUnion(parts: readonly string[]): string {
  return [...new Set(parts)].join(" | ")
}

function escapeTemplatePart(part: string): string {
  return part.replaceAll("`", "\\`").replaceAll("${", "\\${")
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null
}
