// Generated by `tskm gen` — concrete types, no Infer<…>, zod stays the
// runtime validator.
import type { User, UserId } from "./user.schema.gen.ts"
import { userIdSchema, userSchema } from "./user.schema.ts"

const parsed = userSchema.safeParse({
  id: "u1",
  name: "Mio",
  roles: ["admin"],
  nameLength: "Mio",
})

if (parsed.success) {
  const user: User = parsed.data
  console.log("valid user:", user.name, "nameLength:", user.nameLength)
}

const id = userIdSchema.parse("u1") as UserId
console.log("branded id:", id)
