// Generated by `tskm gen`: concrete types, no Infer<…>. Each library stays
// the runtime validator for its own schemas; one compiler typed all three.
import { type } from "arktype"
import * as v from "valibot"
import type { Order } from "./order.schema.gen.ts"
import { orderSchema } from "./order.schema.ts"
import type { Menu, Product, Sku } from "./product.schema.gen.ts"
import { menuSchema, productSchema, skuSchema } from "./product.schema.ts"
import type { User, UserId } from "./user.schema.gen.ts"
import { userIdSchema, userSchema } from "./user.schema.ts"

// --- zod ---
const parsed = userSchema.safeParse({
  id: "u1",
  name: "Mio",
  roles: ["admin"],
  nameLength: "Mio",
})

if (parsed.success) {
  const user: User = parsed.data
  console.log("zod user:", user.name, "nameLength:", user.nameLength)
}

const id = userIdSchema.parse("u1") as UserId
console.log("zod branded id:", id)

// --- valibot ---
const product: Product = v.parse(productSchema, {
  title: "Tea",
  tags: ["drink"],
  titleLength: "Tea",
})
console.log("valibot product:", product.title, "titleLength:", product.titleLength)

const sku: Sku = v.parse(skuSchema, "sku-1")
console.log("valibot branded sku:", sku)

const menu: Menu = v.parse(menuSchema, {
  label: "root",
  items: [{ label: "leaf", items: [] }],
})
console.log("valibot recursive menu:", menu.label, "->", menu.items[0]?.label)

// --- arktype ---
const out = orderSchema({ id: "o1", qty: "3" })
if (!(out instanceof type.errors)) {
  const order: Order = out
  console.log("arktype order:", order.id, "qty:", order.qty, `(${typeof order.qty})`)
}
