// AUTO-GENERATED by tskm. Do not edit.

import type { Brand } from "valibot"
import type { MenuT } from "./product.schema"

export type Product = {
  title: string;
  tags: string[];
  price?: number | undefined;
  titleLength: number;
}

export type Sku = string & Brand<"Sku">

export type Menu = {
  label: string;
  items: MenuT[];
}
