// AUTO-GENERATED by tskm. Do not edit.

import type { $brand } from "zod"
import type { CategoryT } from "./user.schema"

export type User = {
  id: string;
  name: string;
  age?: number | undefined;
  roles: string[];
  nameLength: number;
}

export type UserId = string & $brand<"UserId">

export type Category = {
  name: string;
  children: CategoryT[];
}
