import { writeFileSync } from "node:fs"
import { basename, dirname, extname, join } from "node:path"
import { sourceImportSpecifier } from "./query-core.ts"
import type { ResolvedSchema } from "./resolve.ts"
import { containsTokenOutsideQuotes, referencesTypeOutsideQuotes } from "./token-scan.ts"

const HEADER = "// AUTO-GENERATED by tskm. Do not edit."

/**
 * Library-internal type names that legitimately leak into rendered output (a
 * brand IS `base & Marker<...>`), keyed by the vendor whose types can leak
 * them. Static emit-side knowledge — deliberately not configuration.
 */
interface LeakedTypeImport {
  /** The leaked type identifier as typeToString prints it. */
  readonly token: string
  /** The vendor whose schemas leak it == the module exporting it top-level. */
  readonly module: string
}

const VENDOR_LEAK_TABLE: ReadonlyArray<LeakedTypeImport> = [
  { token: "$brand", module: "zod" },
  { token: "Brand", module: "valibot" },
]

/**
 * Derives the sidecar's `import type` lines from the resolved metadata. Both
 * sources are double-gated so a coincidental name can never pull in a bogus
 * import: vendor leaks require the matching `vendorHint` AND a whole-word token
 * hit; annotation imports require discovery-confirmed export-ness AND an actual
 * type REFERENCE in the body (a property key does not count). An annotation
 * exported under an alias is rebound to the rendered name
 * (`import type { PublicCat as CatT }`).
 */
function collectImportLines(
  resolved: ReadonlyArray<ResolvedSchema>,
  sourceImportPath: string | undefined,
): ReadonlyArray<string> {
  const lines: string[] = []
  for (const entry of VENDOR_LEAK_TABLE) {
    const hit = resolved.some(
      (r) => r.vendorHint === entry.module && containsTokenOutsideQuotes(r.typeString, entry.token),
    )
    if (hit) {
      lines.push(`import type { ${entry.token} } from "${entry.module}"`)
    }
  }
  if (sourceImportPath) {
    /** Rendered (local) name -> the exported name to import it under. */
    const names = new Map<string, string>()
    for (const r of resolved) {
      const annotation = r.recursiveAnnotation
      if (annotation?.exported && referencesTypeOutsideQuotes(r.typeString, annotation.name)) {
        names.set(annotation.name, annotation.exportedAs ?? annotation.name)
      }
    }
    if (names.size > 0) {
      const items = [...names.keys()].sort().map((local) => {
        const exported = names.get(local)
        return exported === local ? local : `${exported} as ${local}`
      })
      lines.push(`import type { ${items.join(", ")} } from "${sourceImportPath}"`)
    }
  }
  return lines
}

/** The sidecar path for a source file: `<base>.gen.ts` next to the source. */
export function sidecarPath(sourceFileAbs: string): string {
  const dir = dirname(sourceFileAbs)
  const base = basename(sourceFileAbs, extname(sourceFileAbs))
  return join(dir, `${base}.gen.ts`)
}

/**
 * Index in `text` of the bracket/brace/paren that closes the one opened at
 * `openIdx`, or -1 if unbalanced. String/template literals are skipped so
 * delimiters inside them are not counted.
 */
function matchingBracket(text: string, openIdx: number): number {
  let depth = 0
  let i = openIdx
  while (i < text.length) {
    const c = text[i]
    if (c === '"' || c === "'" || c === "`") {
      const quote = c
      i++
      while (i < text.length) {
        if (text[i] === "\\") {
          i += 2
          continue
        }
        if (text[i] === quote) {
          i++
          break
        }
        i++
      }
      continue
    }
    if (c === "{" || c === "[" || c === "(") {
      depth++
    } else if (c === "}" || c === "]" || c === ")") {
      depth--
      if (depth === 0) {
        return i
      }
    }
    i++
  }
  return -1
}

/**
 * Deterministic balanced-brace pretty-printer for a single-line type string.
 * Indents one level per open `{`/`[`/`(`, breaks after `;` and structural
 * delimiters. Purely syntactic and stable: the same input always yields the same
 * output, which keeps generated files diff-friendly. String/template literals are
 * preserved verbatim so braces inside them never trigger reindentation.
 */
export function reindentType(single: string): string {
  const text = single.trim()
  // Build into chunks and join once instead of growing a string per character:
  // string concatenation here was a hot allocator in the warm codegen profile.
  const out: string[] = []
  let depth = 0
  let i = 0
  const pad = (d: number): string => "  ".repeat(Math.max(d, 0))

  // Tracks the old `out.endsWith("\n") || out.length === 0` check without
  // re-scanning the accumulator: true while the next push begins a fresh line.
  // Every branch below updates it to mirror what it appends (a `\n`-terminated
  // chunk leaves it true; any other non-empty chunk leaves it false).
  let lineStart = true

  while (i < text.length) {
    // i is bounded by text.length, so the char is always present; the cast only sheds the
    // "| undefined" that noUncheckedIndexedAccess adds (same pattern as the sibling scanners).
    const ch = text[i] as string

    if (ch === '"' || ch === "'" || ch === "`") {
      const quote = ch
      let lit = ch
      i++
      while (i < text.length) {
        const c = text[i]
        lit += c
        i++
        if (c === "\\" && i < text.length) {
          lit += text[i]
          i++
          continue
        }
        if (c === quote) {
          break
        }
      }
      if (lineStart) {
        out.push(pad(depth))
      }
      out.push(lit)
      lineStart = false
      continue
    }

    if (ch === "{" || ch === "[" || ch === "(") {
      if (lineStart) {
        out.push(pad(depth))
      }
      // Empty container: keep `{}` / `[]` / `()` inline.
      const next = text[i + 1]
      if (
        (ch === "{" && next === "}") ||
        (ch === "[" && next === "]") ||
        (ch === "(" && next === ")")
      ) {
        out.push(ch + next)
        lineStart = false
        i += 2
        continue
      }
      // Index-signature key `[key: T]:` — emit the whole `[…]` inline instead of breaking
      // it like a tuple/array. Detected by a matching `]` immediately followed by `:`
      // (a tuple's closing `]` is never followed by `:`). Keeps `record(…)` output readable.
      if (ch === "[") {
        const close = matchingBracket(text, i)
        if (close !== -1) {
          let j = close + 1
          while (j < text.length && (text[j] === " " || text[j] === "\t")) {
            j++
          }
          if (text[j] === ":") {
            out.push(
              `[${text
                .slice(i + 1, close)
                .trim()
                .replace(/\s+/g, " ")}]`,
            )
            lineStart = false
            i = close + 1
            continue
          }
        }
      }
      depth++
      out.push(`${ch}\n`)
      lineStart = true
      i++
      continue
    }

    if (ch === "}" || ch === "]" || ch === ")") {
      depth--
      if (!lineStart) {
        out.push("\n")
      }
      out.push(pad(depth) + ch)
      lineStart = false
      i++
      continue
    }

    if (ch === ";") {
      out.push(";\n")
      lineStart = true
      i++
      // Collapse following whitespace; next token will re-pad.
      while (i < text.length && (text[i] === " " || text[i] === "\t")) {
        i++
      }
      continue
    }

    if (ch === " " && lineStart) {
      i++
      continue
    }

    if (lineStart) {
      out.push(pad(depth))
    }
    out.push(ch)
    lineStart = false
    i++
  }

  return out
    .join("")
    .split("\n")
    .map((line) => line.replace(/\s+$/, ""))
    .filter((line, idx, arr) => !(line === "" && (idx === 0 || arr[idx - 1] === "")))
    .join("\n")
}

export interface EmitResult {
  readonly sidecar: string
  readonly content: string
}

export interface RenderSidecarOptions {
  readonly pretty?: boolean
  /**
   * Import specifier back to the source module (`./<base>`); enables the
   * annotation-import slot. Absent in pure render contexts (no imports emitted).
   */
  readonly sourceImportPath?: string
}

/**
 * Renders the sidecar file content. Detects duplicate type names within the file
 * and throws, since two `export type X` lines would be a hard TS error downstream.
 * Import lines (vendor brand leaks, exported self-annotation types) go right
 * after the header; an import-free render is byte-identical to the historical
 * layout.
 */
export function renderSidecar(
  resolved: ReadonlyArray<ResolvedSchema>,
  options: RenderSidecarOptions = {},
): string {
  const seen = new Set<string>()
  for (const r of resolved) {
    if (seen.has(r.typeName)) {
      throw new Error(
        `tskm: duplicate generated type name "${r.typeName}". Rename the conflicting schema or type alias.`,
      )
    }
    seen.add(r.typeName)
  }

  const pretty = options.pretty ?? true
  const imports = collectImportLines(resolved, options.sourceImportPath)
  const importBlock = imports.length > 0 ? `\n${imports.join("\n")}\n` : ""
  const blocks = resolved.map((r) => {
    const value = pretty ? reindentType(r.typeString) : r.typeString
    return `export type ${r.typeName} = ${value}\n`
  })
  return `${HEADER}\n${importBlock}\n${blocks.join("\n")}`
}

/**
 * Writes the sidecar `<base>.gen.ts` next to the source. Returns the written path
 * and content. Throws on duplicate type names (see {@link renderSidecar}).
 */
export function emitSidecar(
  sourceFileAbs: string,
  resolved: ReadonlyArray<ResolvedSchema>,
  options: { readonly pretty?: boolean } = {},
): EmitResult {
  const sidecar = sidecarPath(sourceFileAbs)
  const content = renderSidecar(resolved, {
    ...options,
    sourceImportPath: sourceImportSpecifier(sourceFileAbs),
  })
  writeFileSync(sidecar, content)
  return { sidecar, content }
}
