import { writeFileSync } from "node:fs"
import { basename, dirname, extname, join } from "node:path"
import type { ResolvedSchema } from "./resolve.ts"

const HEADER = "// AUTO-GENERATED by tskm. Do not edit."

/** The sidecar path for a source file: `<base>.gen.ts` next to the source. */
export function sidecarPath(sourceFileAbs: string): string {
  const dir = dirname(sourceFileAbs)
  const base = basename(sourceFileAbs, extname(sourceFileAbs))
  return join(dir, `${base}.gen.ts`)
}

/**
 * Deterministic balanced-brace pretty-printer for a single-line type string.
 * Indents one level per open `{`/`[`/`(`, breaks after `;` and structural
 * delimiters. Purely syntactic and stable: the same input always yields the same
 * output, which keeps generated files diff-friendly. String/template literals are
 * preserved verbatim so braces inside them never trigger reindentation.
 */
export function reindentType(single: string): string {
  const text = single.trim()
  let out = ""
  let depth = 0
  let i = 0
  const pad = (d: number): string => "  ".repeat(Math.max(d, 0))

  const startsLine = (): boolean => out.length === 0 || out.endsWith("\n")

  while (i < text.length) {
    const ch = text[i]

    if (ch === '"' || ch === "'" || ch === "`") {
      const quote = ch
      let lit = ch
      i++
      while (i < text.length) {
        const c = text[i]
        lit += c
        i++
        if (c === "\\" && i < text.length) {
          lit += text[i]
          i++
          continue
        }
        if (c === quote) {
          break
        }
      }
      if (startsLine()) {
        out += pad(depth)
      }
      out += lit
      continue
    }

    if (ch === "{" || ch === "[" || ch === "(") {
      if (startsLine()) {
        out += pad(depth)
      }
      // Empty container: keep `{}` / `[]` / `()` inline.
      const next = text[i + 1]
      if (
        (ch === "{" && next === "}") ||
        (ch === "[" && next === "]") ||
        (ch === "(" && next === ")")
      ) {
        out += ch + next
        i += 2
        continue
      }
      depth++
      out += `${ch}\n`
      i++
      continue
    }

    if (ch === "}" || ch === "]" || ch === ")") {
      depth--
      if (!startsLine()) {
        out += "\n"
      }
      out += pad(depth) + ch
      i++
      continue
    }

    if (ch === ";") {
      out += ";\n"
      i++
      // Collapse following whitespace; next token will re-pad.
      while (i < text.length && (text[i] === " " || text[i] === "\t")) {
        i++
      }
      continue
    }

    if (ch === " " && startsLine()) {
      i++
      continue
    }

    if (startsLine()) {
      out += pad(depth)
    }
    out += ch
    i++
  }

  return out
    .split("\n")
    .map((line) => line.replace(/\s+$/, ""))
    .filter((line, idx, arr) => !(line === "" && (idx === 0 || arr[idx - 1] === "")))
    .join("\n")
}

export interface EmitResult {
  readonly sidecar: string
  readonly content: string
}

/**
 * Renders the sidecar file content. Detects duplicate type names within the file
 * and throws, since two `export type X` lines would be a hard TS error downstream.
 */
export function renderSidecar(
  resolved: ReadonlyArray<ResolvedSchema>,
  options: { readonly pretty?: boolean } = {},
): string {
  const seen = new Set<string>()
  for (const r of resolved) {
    if (seen.has(r.typeName)) {
      throw new Error(
        `tskm: duplicate generated type name "${r.typeName}". Rename the conflicting schema or type alias.`,
      )
    }
    seen.add(r.typeName)
  }

  const pretty = options.pretty ?? true
  const blocks = resolved.map((r) => {
    const value = pretty ? reindentType(r.typeString) : r.typeString
    return `export type ${r.typeName} = ${value}\n`
  })
  return `${HEADER}\n\n${blocks.join("\n")}`
}

/**
 * Writes the sidecar `<base>.gen.ts` next to the source. Returns the written path
 * and content. Throws on duplicate type names (see {@link renderSidecar}).
 */
export function emitSidecar(
  sourceFileAbs: string,
  resolved: ReadonlyArray<ResolvedSchema>,
  options: { readonly pretty?: boolean } = {},
): EmitResult {
  const sidecar = sidecarPath(sourceFileAbs)
  const content = renderSidecar(resolved, options)
  writeFileSync(sidecar, content)
  return { sidecar, content }
}
