import { describe, expect, it } from "bun:test"
import { renderSidecar } from "../src/emit.ts"

describe("renderSidecar — vendor leak imports (two-stage guard)", () => {
  it("emits the zod $brand import when a zod-derived type leaks the token", () => {
    const out = renderSidecar([
      {
        typeName: "UserId",
        typeString: 'string & $brand<"UserId">',
        sourceName: "userIdSchema",
        vendorHint: "zod",
      },
    ])
    expect(out).toContain('import type { $brand } from "zod"')
    expect(out).toContain('export type UserId = string & $brand<"UserId">')
  })

  it("emits the valibot Brand import for a valibot-derived leak", () => {
    const out = renderSidecar([
      {
        typeName: "UserId",
        typeString: 'string & Brand<"UserId">',
        sourceName: "userIdSchema",
        vendorHint: "valibot",
      },
    ])
    expect(out).toContain('import type { Brand } from "valibot"')
  })

  it("does NOT import for a token match without the matching vendor (guard 1: vendorHint)", () => {
    // `Brand` is a plausible USER type name; a zod-derived type mentioning it
    // must not pull in a bogus valibot import.
    const out = renderSidecar([
      {
        typeName: "Card",
        typeString: "{ brand: Brand; }",
        sourceName: "cardSchema",
        vendorHint: "zod",
      },
    ])
    expect(out).not.toContain("valibot")
  })

  it("does NOT import for a vendor match without the token (guard 2: token scan)", () => {
    const out = renderSidecar([
      {
        typeName: "User",
        typeString: "{ id: string; }",
        sourceName: "userSchema",
        vendorHint: "zod",
      },
    ])
    expect(out).not.toContain("import")
  })

  it("ignores token occurrences inside string-literal types", () => {
    const out = renderSidecar([
      {
        typeName: "Label",
        typeString: '"$brand"',
        sourceName: "labelSchema",
        vendorHint: "zod",
      },
    ])
    expect(out).not.toContain("import")
  })

  it("never imports for tskm-derived types (no vendorHint)", () => {
    const out = renderSidecar([{ typeName: "UserId", typeString: 'string & $brand<"UserId">' }])
    expect(out).not.toContain("import")
  })
})

describe("renderSidecar — recursive annotation imports", () => {
  const annotated = (exported: boolean) =>
    [
      {
        typeName: "Cat",
        typeString: "{ name: string; kitten?: CatT | undefined; }",
        sourceName: "catSchema",
        vendorHint: "zod",
        recursiveAnnotation: { name: "CatT", exported },
      },
    ] as const

  it("imports an EXPORTED annotation type from the source module", () => {
    const out = renderSidecar(annotated(true), { sourceImportPath: "./cat.schema" })
    expect(out).toContain('import type { CatT } from "./cat.schema"')
  })

  it("rebinds an ALIASED export to the rendered name (import { PublicCat as CatT })", () => {
    const out = renderSidecar(
      [
        {
          typeName: "Cat",
          typeString: "{ name: string; kitten?: CatT | undefined; }",
          sourceName: "catSchema",
          vendorHint: "zod",
          recursiveAnnotation: { name: "CatT", exported: true, exportedAs: "PublicCat" },
        },
      ],
      { sourceImportPath: "./cat.schema" },
    )
    expect(out).toContain('import type { PublicCat as CatT } from "./cat.schema"')
  })

  it("does not import when the body never references the annotation", () => {
    const out = renderSidecar(
      [
        {
          typeName: "Cat",
          typeString: "{ name: string; }",
          sourceName: "catSchema",
          vendorHint: "zod",
          recursiveAnnotation: { name: "CatT", exported: true },
        },
      ],
      { sourceImportPath: "./cat.schema" },
    )
    expect(out).not.toContain("import")
  })

  it("does not import without a sourceImportPath (pure render context)", () => {
    const out = renderSidecar(annotated(true))
    expect(out).not.toContain("import")
  })

  it("does not treat a property KEY named like the annotation as a reference", () => {
    const out = renderSidecar(
      [
        {
          typeName: "Odd",
          typeString: "{ CatT: string; }",
          sourceName: "oddSchema",
          vendorHint: "zod",
          recursiveAnnotation: { name: "CatT", exported: true },
        },
      ],
      { sourceImportPath: "./odd.schema" },
    )
    expect(out).not.toContain("import")
  })
})

describe("renderSidecar — legacy layout stability", () => {
  it("keeps the import-free output byte-identical to the historical layout", () => {
    const out = renderSidecar([{ typeName: "Tag", typeString: "string" }])
    expect(out).toBe("// AUTO-GENERATED by tskm. Do not edit.\n\nexport type Tag = string\n")
  })
})
