import { afterEach, describe, expect, it } from "bun:test"
import { mkdtempSync, readFileSync, rmSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import {
  type EmitResult,
  emitSidecar,
  reindentType,
  renderSidecar,
  sidecarPath,
} from "../src/emit.ts"
import type { ResolvedSchema } from "../src/resolve.ts"

const HEADER = "// AUTO-GENERATED by tskm. Do not edit."

describe("sidecarPath", () => {
  it("derives `<base>.gen.ts` next to the source, stripping the .ts extension", () => {
    expect(sidecarPath("/proj/src/account.schema.ts")).toBe("/proj/src/account.schema.gen.ts")
  })

  it("works for a plain .ts file", () => {
    expect(sidecarPath("/a/b/user.ts")).toBe("/a/b/user.gen.ts")
  })

  it("strips only the final extension (.tsx -> base.gen.ts)", () => {
    expect(sidecarPath("/x/widget.tsx")).toBe("/x/widget.gen.ts")
  })

  it("handles a file with no directory component", () => {
    expect(sidecarPath("foo.ts")).toBe("foo.gen.ts")
  })

  it("handles a file with no extension at all", () => {
    expect(sidecarPath("/tmp/plain")).toBe("/tmp/plain.gen.ts")
  })
})

describe("reindentType — single line / leaf", () => {
  it("returns a trimmed scalar type unchanged", () => {
    expect(reindentType("string")).toBe("string")
  })

  it("trims surrounding whitespace", () => {
    expect(reindentType("   number   ")).toBe("number")
  })

  it("keeps empty containers inline", () => {
    expect(reindentType("{}")).toBe("{}")
    expect(reindentType("[]")).toBe("[]")
    expect(reindentType("()")).toBe("()")
  })

  it("keeps a Record with empty-object inline portions correct", () => {
    expect(reindentType("Record<string, {}>")).toBe("Record<string, {}>")
  })

  it("emits an index-signature key inline (its `[…]` is not broken like a tuple)", () => {
    // `{ [key: string]: number }` — the `[key: string]` head is detected via a matching
    // `]` immediately followed by `:` and kept on one line; only the object breaks.
    expect(reindentType("{ [key: string]: number }")).toBe("{\n  [key: string]: number\n}")
    // The index value still reindents normally.
    expect(reindentType("{ [k: string]: { n: number } }")).toBe(
      "{\n  [k: string]: {\n    n: number\n  }\n}",
    )
  })

  it("preserves a string literal (with escaped quote) inside an index-signature head verbatim", () => {
    // The literal's escaped `\"` must not be treated as the closing quote, and the `]` inside
    // the string (if any) must not close the bracket — the scanner skips string bodies.
    expect(reindentType('{ [k: "a\\"b"]: number }')).toBe('{\n  [k: "a\\"b"]: number\n}')
  })
})

describe("reindentType — nested objects", () => {
  it("indents one level per open brace and dedents on close", () => {
    const out = reindentType("{ a: string; b: number }")
    expect(out).toBe("{\n  a: string;\n  b: number\n}")
  })

  it("nests two levels with cumulative indentation", () => {
    const out = reindentType("{ user: { name: string } }")
    expect(out).toBe("{\n  user: {\n    name: string\n  }\n}")
  })

  it("breaks after each semicolon and collapses trailing whitespace before the next key", () => {
    const out = reindentType("{ a: string;   b: number }")
    // The whitespace after `;` is collapsed; `b` is re-padded at depth 1.
    expect(out).toBe("{\n  a: string;\n  b: number\n}")
  })

  it("handles arrays/tuples with bracket indentation (commas do not break lines)", () => {
    // Only `;` triggers a line break; commas stay inline within the bracketed body.
    const out = reindentType("[ string, number ]")
    expect(out).toBe("[\n  string, number\n]")
  })

  it("keeps an index-signature key inline (record output), unlike a tuple", () => {
    // `[x: string]` is a key, not a tuple: its `]` is followed by `:`, so it stays on
    // one line. The value still formats normally.
    expect(reindentType("{ [x: string]: number }")).toBe("{\n  [x: string]: number\n}")
    expect(reindentType("{ [key: string]: Json; }")).toBe("{\n  [key: string]: Json;\n}")
  })

  it("formats a record nested in a union without splitting the index signature", () => {
    const out = reindentType("string | { [x: string]: Json; } | null")
    expect(out).toBe("string | {\n  [x: string]: Json;\n} | null")
  })

  it("keeps the index signature inline even when whitespace separates the ] and the :", () => {
    // The `]`-then-`:` lookahead skips intervening spaces/tabs, so `[x: string] : T`
    // is still recognized as a key (not a tuple) and the whole `[...]` stays inline on one
    // line (rather than being broken open like a tuple).
    expect(reindentType("{ [x: string] : number }")).toBe("{\n  [x: string] : number\n}")
  })

  it("does not treat a bracket whose contents are a string literal as a key (literal-skipping)", () => {
    // The matching-bracket scan must skip string literals, so a `]` *inside* a literal
    // does not prematurely close the `[`. Here the tuple element is the string "]"; the
    // real closing `]` is the second one, and it is not followed by `:`, so the bracket
    // breaks like a normal tuple rather than collapsing into an index-signature key.
    expect(reindentType('[ "]" ]')).toBe('[\n  "]"\n]')
  })

  it("indents parenthesized groups", () => {
    const out = reindentType("( string | number )")
    expect(out).toBe("(\n  string | number\n)")
  })
})

describe("reindentType — string/template literals preserved verbatim", () => {
  it("does not reindent braces inside a double-quoted string literal", () => {
    const out = reindentType('{ tag: "{not a brace}" }')
    expect(out).toBe('{\n  tag: "{not a brace}"\n}')
  })

  it("does not reindent braces inside a single-quoted literal", () => {
    const out = reindentType("{ tag: '{x}' }")
    expect(out).toBe("{\n  tag: '{x}'\n}")
  })

  it("preserves template-literal contents", () => {
    const out = reindentType("{ k: `a;b{c}` }")
    expect(out).toBe("{\n  k: `a;b{c}`\n}")
  })

  it("respects backslash-escaped quotes inside a string literal", () => {
    // The escaped quote must NOT terminate the literal early.
    const out = reindentType('"a\\"b"')
    expect(out).toBe('"a\\"b"')
  })

  it("treats a literal that begins at the start of a line by padding it", () => {
    const out = reindentType('{ "key": string }')
    expect(out).toBe('{\n  "key": string\n}')
  })
})

describe("reindentType — collapses blank lines and trailing whitespace", () => {
  it("does not leave duplicate consecutive blank lines from semicolon at end", () => {
    const out = reindentType("{ a: string; }")
    // Trailing `;` produces a break then close brace; no stray blank line remains.
    expect(out).toBe("{\n  a: string;\n}")
    expect(out).not.toContain("\n\n")
  })

  it("strips trailing whitespace from every produced line", () => {
    const out = reindentType("{ a: string }")
    for (const line of out.split("\n")) {
      expect(line).toBe(line.replace(/\s+$/, ""))
    }
  })
})

describe("renderSidecar", () => {
  const make = (typeName: string, typeString: string): ResolvedSchema => ({
    typeName,
    typeString,
  })

  it("emits the header banner followed by exported type aliases", () => {
    const content = renderSidecar([make("User", "{ id: string }")])
    expect(content.startsWith(`${HEADER}\n\n`)).toBe(true)
    expect(content).toContain("export type User = {")
    expect(content).toContain("  id: string")
  })

  it("pretty-prints by default (multi-line nested type)", () => {
    const content = renderSidecar([make("User", "{ id: string; age: number }")])
    expect(content).toContain("export type User = {\n  id: string;\n  age: number\n}\n")
  })

  it("when pretty:false keeps the typeString verbatim on one line", () => {
    const content = renderSidecar([make("User", "{ id: string; age: number }")], {
      pretty: false,
    })
    expect(content).toContain("export type User = { id: string; age: number }\n")
    expect(content).not.toContain("export type User = {\n")
  })

  it("when pretty:true explicitly, reindents", () => {
    const content = renderSidecar([make("User", "{ id: string }")], { pretty: true })
    expect(content).toContain("export type User = {\n  id: string\n}\n")
  })

  it("renders multiple types each as their own export, joined by a blank line", () => {
    const content = renderSidecar([make("A", "string"), make("B", "number")])
    expect(content).toContain("export type A = string\n")
    expect(content).toContain("export type B = number\n")
    // Blocks are joined with a newline separator.
    expect(content).toContain("export type A = string\n\nexport type B = number\n")
  })

  it("renders an empty input as just the header (no exports)", () => {
    const content = renderSidecar([])
    expect(content).toBe(`${HEADER}\n\n`)
  })

  it("throws on duplicate generated type names with a descriptive message", () => {
    expect(() => renderSidecar([make("Dup", "string"), make("Dup", "number")])).toThrow(
      /duplicate generated type name "Dup"/,
    )
  })

  it("allows distinct type names that share a typeString", () => {
    expect(() => renderSidecar([make("A", "string"), make("B", "string")])).not.toThrow()
  })
})

describe("emitSidecar", () => {
  const tempDirs: string[] = []

  const makeTemp = (): string => {
    const dir = mkdtempSync(join(tmpdir(), "tskm-emit-"))
    tempDirs.push(dir)
    return dir
  }

  afterEach(() => {
    while (tempDirs.length > 0) {
      const dir = tempDirs.pop()
      if (dir) {
        rmSync(dir, { recursive: true, force: true })
      }
    }
  })

  it("writes `<base>.gen.ts` to disk and returns the path + content", () => {
    const dir = makeTemp()
    const src = join(dir, "account.schema.ts")
    const result: EmitResult = emitSidecar(src, [
      { typeName: "Account", typeString: "{ id: string }" },
    ])

    const expectedSidecar = join(dir, "account.schema.gen.ts")
    expect(result.sidecar).toBe(expectedSidecar)

    const onDisk = readFileSync(expectedSidecar, "utf8")
    expect(onDisk).toBe(result.content)
    expect(onDisk).toContain(HEADER)
    expect(onDisk).toContain("export type Account = {\n  id: string\n}")
  })

  it("honors pretty:false through to the written file", () => {
    const dir = makeTemp()
    const src = join(dir, "u.ts")
    const result = emitSidecar(src, [{ typeName: "U", typeString: "{ a: string; b: number }" }], {
      pretty: false,
    })
    const onDisk = readFileSync(result.sidecar, "utf8")
    expect(onDisk).toContain("export type U = { a: string; b: number }\n")
  })

  it("writes header-only content for an empty resolved list", () => {
    const dir = makeTemp()
    const src = join(dir, "empty.ts")
    const result = emitSidecar(src, [])
    expect(readFileSync(result.sidecar, "utf8")).toBe(`${HEADER}\n\n`)
  })

  it("propagates the duplicate-name error before writing", () => {
    const dir = makeTemp()
    const src = join(dir, "dup.ts")
    expect(() =>
      emitSidecar(src, [
        { typeName: "X", typeString: "string" },
        { typeName: "X", typeString: "number" },
      ]),
    ).toThrow(/duplicate generated type name "X"/)
  })

  it("overwrites an existing sidecar on a second emit (no caching/no-op layer)", () => {
    const dir = makeTemp()
    const src = join(dir, "rewrite.ts")
    const first = emitSidecar(src, [{ typeName: "T", typeString: "string" }])
    expect(readFileSync(first.sidecar, "utf8")).toContain("export type T = string")

    const second = emitSidecar(src, [{ typeName: "T", typeString: "number" }])
    expect(second.sidecar).toBe(first.sidecar)
    const onDisk = readFileSync(second.sidecar, "utf8")
    expect(onDisk).toContain("export type T = number")
    expect(onDisk).not.toContain("export type T = string")
  })
})
