import { afterAll, describe, expect, it } from "bun:test"
import { existsSync, readFileSync, rmSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { generate } from "../src/index.ts"
import { runTsgoNoEmit } from "./typecheck-harness.ts"

/**
 * Standard Schema interop — the resolution smoke (plan step 8). Proves the two
 * load-bearing claims every later scenario builds on, BEFORE those scenarios
 * exist: (1) zod resolves from the fixture through bun's isolated-install
 * upward walk (compiler devDependency, no fixture node_modules, no tsconfig
 * paths entry), for BOTH the tsgo project load and the checker query; (2) the
 * hybrid discovery -> guard -> `~standard` query pipeline emits a compilable
 * sidecar for an external schema. Resolution success and emit-ability are
 * asserted SEPARATELY (a failure must say which one broke).
 */

const fixtureRoot = fileURLToPath(new URL("./fixtures/standard", import.meta.url))
const sidecar = fileURLToPath(
  new URL("./fixtures/standard/src/zod-basic.schema.gen.ts", import.meta.url),
)
const queryFile = fileURLToPath(
  new URL("./fixtures/standard/src/zod-basic.schema.tskm-query.ts", import.meta.url),
)

afterAll(() => {
  for (const f of [sidecar, queryFile]) {
    if (existsSync(f)) rmSync(f)
  }
})

describe("standard schema interop (real tsgo) — resolution smoke", () => {
  it("resolves a zod schema to a fully-expanded sidecar type", async () => {
    const result = await generate({
      root: fixtureRoot,
      config: { mode: "sidecar", include: ["src/zod-basic.schema.ts"], tsconfig: "tsconfig.json" },
    })

    expect(result.files.length).toBe(1)
    expect(result.files[0]?.typeNames).toEqual(["Account"])

    const gen = readFileSync(sidecar, "utf8")
    expect(gen).toContain("export type Account = {")
    expect(gen).toContain("id: string")
    // zod's optional() marks the KEY optional (unlike tskm's value-union form)
    expect(gen).toContain("age?: number | undefined")
    expect(gen).toContain("roles: string[]")
    expect(gen).toContain("bio: string | null")
    // transform's POST-transform output type
    expect(gen).toContain("nameLength: number")
  }, 60_000)

  it("silently drops a guarded candidate that is not a schema", () => {
    // `parsedValue` (a z.string().parse(...) call) was a syntactic candidate;
    // the emitted sidecar must not contain it, and no diagnostic refers to it.
    const gen = readFileSync(sidecar, "utf8")
    expect(gen).not.toContain("ParsedValue")
    expect(gen).not.toContain("NotASchema")
  })

  it("emits a sidecar the real tsgo accepts (emit-ability, separate from resolution)", () => {
    const check = runTsgoNoEmit(fixtureRoot)
    expect(check.output).not.toContain("error TS")
    expect(check.ok).toBe(true)
  }, 120_000)

  it("leaves no query files behind", () => {
    expect(existsSync(queryFile)).toBe(false)
  })
})

describe("standard schema interop (real tsgo) — post-resolution compile gate", () => {
  const leakSidecar = fileURLToPath(
    new URL("./fixtures/standard/src/zod-leak.schema.gen.ts", import.meta.url),
  )
  const leakVerify = fileURLToPath(
    new URL("./fixtures/standard/src/zod-leak.schema.verify.tskm-query.ts", import.meta.url),
  )

  afterAll(() => {
    for (const f of [leakSidecar, leakVerify]) {
      if (existsSync(f)) rmSync(f)
    }
  })

  it("refuses to write a sidecar whose rendered type cannot compile, preserving the old output", async () => {
    // Pre-seed a known-good previous sidecar: the gate must leave it untouched.
    const previous = "// AUTO-GENERATED by tskm. Do not edit.\n\nexport type Weird = { ok: true }\n"
    const { writeFileSync } = await import("node:fs")
    writeFileSync(leakSidecar, previous)

    const result = await generate({
      root: fixtureRoot,
      config: { mode: "sidecar", include: ["src/zod-leak.schema.ts"], tsconfig: "tsconfig.json" },
    })

    // (iii) diagnostics: the gate names the failure and the fail-closed outcome
    expect(result.diagnostics.join("\n")).toContain("do not compile")
    expect(result.diagnostics.join("\n")).toContain("Existing output left untouched")
    // (i) resolution outcome: no file emitted for this source
    expect(result.files).toHaveLength(0)
    // (ii) emit-ability outcome: the previous sidecar is byte-identical
    expect(readFileSync(leakSidecar, "utf8")).toBe(previous)
    // and the verify probe never survives
    expect(existsSync(leakVerify)).toBe(false)
  }, 60_000)
})

const fx = (rel: string) =>
  fileURLToPath(new URL(`./fixtures/standard/src/${rel}`, import.meta.url))

describe("standard schema interop (real tsgo) — per-library scenarios", () => {
  const artifacts = [
    fx("valibot.schema.gen.ts"),
    fx("arktype.schema.gen.ts"),
    fx("zod-brand.schema.gen.ts"),
    fx("zod-recursive.schema.gen.ts"),
    fx("zod-recursive-alias.schema.gen.ts"),
    fx("zod-recursive-local.schema.gen.ts"),
    fx("mixed.schema.gen.ts"),
    fx("probe.check.ts"),
  ]
  afterAll(() => {
    for (const f of artifacts) {
      if (existsSync(f)) rmSync(f)
    }
  })

  const gen = (include: string) =>
    generate({
      root: fixtureRoot,
      config: { mode: "sidecar", include: [include], tsconfig: "tsconfig.json" },
    })

  it("valibot: basic + pipe transform + GenericSchema recursion + brand", async () => {
    const result = await gen("src/valibot.schema.ts")
    // (i) resolution
    expect(result.files[0]?.typeNames).toEqual(["User", "Node", "Uid"])
    const out = readFileSync(fx("valibot.schema.gen.ts"), "utf8")
    expect(out).toContain("age?: number | undefined")
    expect(out).toContain("score: number") // post-transform output
    // the annotated root renders as the named reference itself — semantically
    // exact: the user's interface IS the type
    expect(out).toContain("export type Node = VNode")
    expect(out).toContain('import type { VNode } from "./valibot.schema"')
    expect(out).toContain('import type { Brand } from "valibot"')
    expect(out).toContain('Brand<"Uid">')
  }, 60_000)

  it("arktype: basic object", async () => {
    const result = await gen("src/arktype.schema.ts")
    expect(result.files[0]?.typeNames).toEqual(["User"])
    const out = readFileSync(fx("arktype.schema.gen.ts"), "utf8")
    expect(out).toContain("name: string")
    expect(out).toContain("age?: number | undefined")
  }, 60_000)

  it("zod: brand emits the $brand import and stays nominal (probe)", async () => {
    const result = await gen("src/zod-brand.schema.ts")
    expect(result.files[0]?.typeNames).toEqual(["UserId", "Card"])
    const out = readFileSync(fx("zod-brand.schema.gen.ts"), "utf8")
    // (i) resolution: raw rendering for the top-level brand, no prototype explosion
    expect(out).toContain('export type UserId = string & $brand<"UserId">')
    expect(out).toContain('import type { $brand } from "zod"')
    expect(out).not.toContain("toUpperCase") // no String prototype leak

    // (ii) emit-ability + nominal semantics, asserted at the value level
    const { writeFileSync } = await import("node:fs")
    writeFileSync(
      fx("probe.check.ts"),
      [
        'import type { UserId } from "./zod-brand.schema.gen.ts"',
        "declare const id: UserId",
        "const base: string = id",
        "// @ts-expect-error a plain string must not be assignable to the branded type",
        'const nominal: UserId = "plain"',
        "export const ok = [base, nominal]",
        "",
      ].join("\n"),
    )
    const check = runTsgoNoEmit(fixtureRoot)
    expect(check.output).not.toContain("error TS")
    expect(check.ok).toBe(true)
  }, 120_000)

  it("zod: exported self-annotation recursion imports the annotation type", async () => {
    const result = await gen("src/zod-recursive.schema.ts")
    expect(result.files[0]?.typeNames).toEqual(["Cat"])
    const out = readFileSync(fx("zod-recursive.schema.gen.ts"), "utf8")
    expect(out).toContain('import type { CatT } from "./zod-recursive.schema"')
    expect(out).toContain("CatT")
  }, 60_000)

  it("zod: an ALIASED exported self-annotation imports the type rebound to its rendered name", async () => {
    const result = await gen("src/zod-recursive-alias.schema.ts")
    // (i) resolution: the schema resolves and the file passes the compile gate
    // (a written sidecar IS the gate's emit-ability verdict)
    expect(result.diagnostics).toHaveLength(0)
    expect(result.files[0]?.typeNames).toEqual(["AliasCat"])
    const out = readFileSync(fx("zod-recursive-alias.schema.gen.ts"), "utf8")
    expect(out).toContain(
      'import type { PublicCatT as AliasCatT } from "./zod-recursive-alias.schema"',
    )
    expect(out).toContain("AliasCatT")
  }, 60_000)

  it("zod: a LOCAL self-annotation is skipped with the export-it diagnostic, leaking nothing", async () => {
    const result = await gen("src/zod-recursive-local.schema.ts")
    // (iii) diagnostics name the fix
    expect(result.diagnostics.join("\n")).toContain("export type CatLocalT = ...")
    // (i) nothing resolved for this file
    expect(result.files).toHaveLength(0)
    // (ii) no sidecar with a bare un-importable name
    expect(existsSync(fx("zod-recursive-local.schema.gen.ts"))).toBe(false)
  }, 60_000)

  it("mixed file: tskm and zod schemas land in ONE sidecar", async () => {
    const result = await gen("src/mixed.schema.ts")
    expect(result.files[0]?.typeNames).toEqual(["Core", "Zod"])
    const out = readFileSync(fx("mixed.schema.gen.ts"), "utf8")
    expect(out).toContain("export type Core = {")
    expect(out).toContain("id: string")
    expect(out).toContain("export type Zod = {")
    expect(out).toContain("label: string")
  }, 60_000)

  it("opt-out (schemaSources: []) discovers no external schemas", async () => {
    const result = await generate({
      root: fixtureRoot,
      config: {
        mode: "sidecar",
        include: ["src/zod-basic.schema.ts"],
        tsconfig: "tsconfig.json",
        schemaSources: [],
      },
    })
    expect(result.files).toHaveLength(0)
  }, 60_000)

  it("regenerating produces byte-identical output (idempotency — the watch-loop guard)", async () => {
    await gen("src/mixed.schema.ts")
    const first = readFileSync(fx("mixed.schema.gen.ts"), "utf8")
    await gen("src/mixed.schema.ts")
    expect(readFileSync(fx("mixed.schema.gen.ts"), "utf8")).toBe(first)
  }, 60_000)
})

describe("standard schema interop (real tsgo) — annotation-free recursion boundary pin", () => {
  const badRoot = fileURLToPath(new URL("./fixtures/standard-bad", import.meta.url))
  const badSidecar = fileURLToPath(
    new URL("./fixtures/standard-bad/src/zod-getter.schema.gen.ts", import.meta.url),
  )

  afterAll(() => {
    if (existsSync(badSidecar)) rmSync(badSidecar)
  })

  // Pins the spike-verified behavior: zod itself self-truncates annotation-free
  // recursion (never TS2589), so the emitted type carries `any` at the cut —
  // FAITHFUL to what z.infer shows in the user's editor. A future regression to
  // a hard failure (or to silent full-`any`) breaks this pin. Full fidelity
  // requires the library-idiomatic self annotation (README known limits).
  it("emits the degraded (self-truncated) type zod infers, without failing", async () => {
    const result = await generate({
      root: badRoot,
      config: { mode: "sidecar", include: ["src/*.schema.ts"], tsconfig: "tsconfig.json" },
    })
    expect(result.files).toHaveLength(1)
    expect(result.diagnostics).toHaveLength(0)
    const out = readFileSync(badSidecar, "utf8")
    expect(out).toContain("export type Cat = {")
    expect(out).toContain("kitten: any")
  }, 60_000)
})

describe("standard schema interop — inplace gating", () => {
  const inplaceSource = fx("inplace-ext.ts")

  afterAll(() => {
    if (existsSync(inplaceSource)) rmSync(inplaceSource)
  })

  it("an external alias in inplace mode is skipped with an explicit unsupported diagnostic", async () => {
    const source = [
      'import { z } from "zod"',
      "const cfgSchema = z.object({ debug: z.boolean() })",
      "export type Cfg = Infer<typeof cfgSchema>",
      "",
    ].join("\n")
    const { writeFileSync } = await import("node:fs")
    writeFileSync(inplaceSource, source)

    const result = await generate({
      root: fixtureRoot,
      config: { mode: "inplace", include: ["src/inplace-ext.ts"], tsconfig: "tsconfig.json" },
    })

    // (iii) explicit diagnostic, never silent staleness
    const text = result.diagnostics.join("\n")
    expect(text).toContain("inplace mode supports only tskm schemas")
    expect(text).toContain("zod")
    // (i)/(ii) the source is untouched
    expect(result.files).toHaveLength(0)
    expect(readFileSync(inplaceSource, "utf8")).toBe(source)
  }, 60_000)
})
